# Generated by Django 5.0.4 on 2024-05-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('temp', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('pressao', models.TextField(max_length=10)),
            ],
        ),
    ]
